### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by hibento** [svdo/swift-netutils#1]
Hi Stefan,

did you ever consider supporting [carthage](https://github.com/Carthage/)? It would be pretty simple, you just need to share you [build scheme](https://github.com/Carthage/Carthage#share-your-xcode-schemes) - I tried it locally and it work's perfectly.

**Comment by svdo** [comment]
Hi Christian,

I know about carthage, but I never used it. Do you recommend it, and if so: why and for what situations? 

I shared the NetUtils scheme and pushed on master. Do you need a new tag in order to be able to use this with carthage?

Stefan

**Comment by steffensc** [comment]
Well that´s kind of a [philosophical question](https://github.com/Carthage/Carthage#differences-between-carthage-and-cocoapods). But I like the minimal approach from Carthage and - at least for my projects - it´s much easier to maintain the project structure myself.

I just pulled your commit, works perfect. Maybe [you could declare your projects compatibility](https://github.com/Carthage/Carthage#declare-your-compatibility)

**Comment by svdo** [comment]
Released a new version and declared compatibility.
