### ISSUE TITLE
Support Xcode 9 & Swift 4

### ISSUE THREAD

**Issue by ThomasLee969** [svdo/swift-netutils#12]
As in Xcode 9 `ifaddrs` is included in `Darwin`,  the project will no longer compile as `ifaddrs` is defined twice.

I've created a separate branch in my fork: https://github.com/ThomasLee969/swift-netutils/tree/swift4 . Maybe we can add a `swift4` branch here?

**Comment by svdo** [comment]
Sure, I created the branch.
