### ISSUE TITLE
Support SSID detection

### ISSUE THREAD

**Issue by hibento** [svdo/swift-netutils#2]
Hi there,

wouldn't it be interesting to extend your library? A WLAN SSID detection / extraction would be nice.

There´s an existing [piece of code](http://stackoverflow.com/a/32833495/2953963) you could use, even tough it's declared deprecated (Apple officially recommends it this way).

**Comment by hibento** [comment]
#3

**Comment by svdo** [comment]
Sorry, not going to add this. It's not what this library is about, and I don't want to support this deprecated API in any case (I'm pretty sure it will disappear in iOS 10).
