### ISSUE TITLE
No longer building with CocoaPods

### ISSUE THREAD

**Issue by mikemee** [svdo/swift-netutils#4]
I'm currently trying to solve the same problem you so nicely documented in https://ind.ie/labs/blog/using-system-headers-in-swift/.  Finally, after stripping my library down, piece by piece by painful piece, I was still getting errors, and so I tried with yours and found it's no longer working there either.  I'm hoping you have some insights!

Here's what I did, and the results:

```
$ git clone https://github.com/svdo/swift-netutils.git
Cloning into 'swift-netutils'...
....
$ cd swift-netutils/
$ pod --version
0.39.0
$ xcodebuild -version
Xcode 7.2
Build version 7C68
$ pod lib lint NetUtils.podspec.json

 -> NetUtils (1.3.2)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  /Users/path/to/swift-netutils/NetUtils/Interface.swift:4:8: error: no such module 'ifaddrs'

[!] NetUtils did not pass validation, due to 2 errors.
You can use the `--no-clean` option to inspect any issue.
$
```
Thanks in advance...!

**Comment by mikemee** [comment]
Ah, but `pod spec lint` does work.

Perhaps this is the issue: https://github.com/CocoaPods/CocoaPods/issues/4607

**Comment by mikemee** [comment]
As this seems to be a CocoaPods specific issue, I'm going to close this.  Of course feel free to re-open if you feel it's useful to others.

**Comment by svdo** [comment]
Hi Mike, I recall having similar issues (that it didn't seem to work but `pod spec lint` did work). Glad you were able to work it out!
